# tasks file
---
- name: install
  ansible.builtin.apt:
    name: "{{ rsyslog_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-install

# workaround for: https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/1256695/comments/5
- name: fix dir permissions
  ansible.builtin.file:
    path: /var/log
    owner: "{{ rsyslog_var_log_user }}"
    group: "{{ rsyslog_var_log_group }}"
    mode: "{{ rsyslog_var_log_mode }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-permissions

- name: apparmor | install
  ansible.builtin.apt:
    name:
      - apparmor-utils
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-apparmor

- name: apparmor | find profiles  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    find /etc/apparmor.d -name "*syslog*" | sort
  failed_when: false
  changed_when: false
  register: _find_profiles
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-apparmor
    - rsyslog-configuration-apparmor-debug

- name: apparmor | find homes
  ansible.builtin.shell: >
    true
    && echo {{ '~' + ansible_facts['env']['USER'] }}
    && echo {{ '~' + ansible_facts['env']['SUDO_USER'] }}
  failed_when: false
  changed_when: false
  register: _find_homes
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-apparmor
    - rsyslog-configuration-apparmor-find-homes

- name: apparmor | fill profile
  ansible.builtin.copy:
    content: |
      {% for line in _find_homes.stdout_lines | unique %}
      {{ line }}/.ansible/tmp/** r,
      {% endfor %}
    dest: "{{ rsyslog_apparmor_profile_local }}"
    owner: root
    group: root
    mode: 0640
    force: true
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-apparmor
    - rsyslog-configuration-apparmor-fill-profile

- name: apparmor | cat profile
  ansible.builtin.command: >
    cat {{ rsyslog_apparmor_profile_local }}
  failed_when: false
  changed_when: false
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-apparmor
    - rsyslog-configuration-apparmor-debug

- name: apparmor | apply profile
  ansible.builtin.shell: >
    apparmor_parser -r -W --debug {{ rsyslog_apparmor_profile }}
  failed_when: false
  changed_when: false
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-apparmor
    - rsyslog-configuration-apparmor-debug

- name: try | catch
  block:
    - name: update specific configuration files
      ansible.builtin.template:
        src: etc/rsyslog.d/rsyslog.conf.j2
        dest: "/etc/rsyslog.d/{{ item.key }}.conf"
        validate: "{{ 'rsyslogd -N1 -f %s' if item.value.validate | default(true) else 'true %s' }}"
        owner: root
        group: root
        mode: 0440
      with_dict: "{{ rsyslog_rsyslog_d_files }}"
      when: item.value.state | default('present') == 'present'
      notify: restart rsyslog
      tags:
        - configuration
        - rsyslog
        - rsyslog-configuration
        - rsyslog-configuration-rsyslog-d

    - name: remove configurations
      ansible.builtin.file:
        dest: "/etc/rsyslog.d/{{ item.key }}.conf"
        state: absent
      with_dict: "{{ rsyslog_rsyslog_d_files }}"
      when: item.value.state | default('present') == 'absent'
      notify: restart rsyslog
      tags:
        - configuration
        - rsyslog
        - rsyslog-configuration
        - rsyslog-configuration-rsyslog-d

    - name: update global configuration file
      ansible.builtin.template:
        src: "{{ rsyslog_global_config_file.lstrip('/') }}.j2"
        dest: "{{ rsyslog_global_config_file }}"
        validate: "{{ 'rsyslogd -N1 -f %s' if rsyslog_global_config_file_validate else 'true %s' }}"
        owner: root
        group: root
        mode: 0440
      tags:
        - configuration
        - rsyslog
        - rsyslog-configuration
        - rsyslog-configuration-rsyslog
  rescue:
    - name: apparmor | get errors  # noqa risky-shell-pipe
      ansible.builtin.shell: >
        grep -R 'apparmor="DENIED"' /var/log | grep syslog
      failed_when: false
      changed_when: false
      tags:
        - configuration
        - rsyslog
        - rsyslog-configuration
        - rsyslog-configuration-apparmor
        - rsyslog-configuration-apparmor-debug

    - name: fail
      ansible.builtin.fail:
        msg: 'apparmor="DENIED"'
      tags:
        - configuration
        - rsyslog
        - rsyslog-configuration
        - rsyslog-configuration-fail

- name: start and enable service
  ansible.builtin.service:
    name: rsyslog
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rsyslog
    - rsyslog-start-enable-service
