---
- name: Converge
  hosts: all
  become: true
  roles:
    - ../../../
  vars:
    rsyslog_apparmor_extend_profile: true
    rsyslog_apparmor_utils_install: true
    rsyslog_apparmor_debug: true

    rsyslog_rsyslog_d_files:
      50-default: "{{ rsyslog_rsyslog_d_presets_50_default | combine(rsyslog_rsyslog_d_presets_validate_false) }}"

    rsyslog_global_config_file_validate: false
