---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: apparmor | disable
      ansible.builtin.shell: >
        true
        && mkdir -p /etc/apparmor.d/disable
        && ln -s /etc/apparmor.d/usr.sbin.rsyslogd /etc/apparmor.d/disable/
        && apparmor_parser -R /etc/apparmor.d/usr.sbin.rsyslogd
      failed_when: false
      changed_when: false
